/**
 * Product catalog with scientific / technical specifications
 * Engineer Hossam Ramadan Store
 */
const PRODUCTS = [
  {
    id: "P001",
    name: "Fluke 87V True RMS Industrial Multimeter",
    category: "electronics",
    price: 449.99,
    originalPrice: 529.99,
    rating: 4.8,
    reviews: 2847,
    prime: true,
    badge: "Best Seller",
    image: "multimeter",
    description: "Professional-grade digital multimeter with 0.05% DC accuracy for industrial diagnostics.",
    specs: {
      "DC Voltage Range": "400 mV – 1000 V",
      "AC Voltage Range": "400 mV – 1000 V",
      "DC Current": "400 µA – 10 A",
      "Resistance": "400 Ω – 50 MΩ",
      "Frequency": "0.5 Hz – 200 kHz",
      "Temperature": "-200 °C to +1090 °C",
      "Display": "Dual 6000-count LCD",
      "Safety Rating": "CAT IV 600 V / CAT III 1000 V",
      "Accuracy (DC V)": "±(0.05% + 1 digit)",
      "Operating Temp": "-10 °C to +55 °C",
    },
  },
  {
    id: "P002",
    name: "Raspberry Pi 5 — 8 GB RAM Development Board",
    category: "electronics",
    price: 79.99,
    originalPrice: 89.99,
    rating: 4.7,
    reviews: 5621,
    prime: true,
    badge: "Amazon's Choice",
    image: "rpi",
    description: "Next-gen single-board computer with BCM2712 quad-core ARM Cortex-A76 @ 2.4 GHz.",
    specs: {
      "Processor": "Broadcom BCM2712, Quad-core Cortex-A76 @ 2.4 GHz",
      "RAM": "8 GB LPDDR4X-4267",
      "GPU": "VideoCore VII",
      "Storage": "MicroSD + PCIe 2.0 x1 (NVMe support)",
      "Connectivity": "Dual-band Wi-Fi 802.11ac, Bluetooth 5.0",
      "USB Ports": "2× USB 3.0, 2× USB 2.0",
      "Video Output": "2× micro-HDMI 4Kp60",
      "GPIO": "40-pin header",
      "Power Input": "5 V / 5 A (USB-C PD)",
      "Dimensions": "85 × 56 mm",
    },
  },
  {
    id: "P003",
    name: "Mitutoyo 500-196-30 Digital Caliper 0-150mm",
    category: "tools",
    price: 124.50,
    originalPrice: 149.00,
    rating: 4.9,
    reviews: 1893,
    prime: true,
    badge: "Top Rated",
    image: "caliper",
    description: "Absolute encoder digital caliper with IP67 protection and ±0.01 mm accuracy.",
    specs: {
      "Measuring Range": "0 – 150 mm (0 – 6 in)",
      "Resolution": "0.01 mm / 0.0005 in",
      "Accuracy": "±0.02 mm",
      "Repeatability": "±0.01 mm",
      "Material": "Hardened stainless steel",
      "Protection": "IP67 (coolant proof)",
      "Display": "LCD with inch/mm toggle",
      "Battery Life": "~3.5 years (SR44)",
      "Standard": "DIN 862 / ISO 13385",
      "Mass": "167 g",
    },
  },
  {
    id: "P004",
    name: "Siemens LOGO! 8.3 PLC Starter Kit",
    category: "automation",
    price: 389.00,
    originalPrice: 459.00,
    rating: 4.6,
    reviews: 412,
    prime: false,
    badge: "Industrial Grade",
    image: "plc",
    description: "Compact logic module for small automation tasks with Ethernet and web server.",
    specs: {
      "CPU": "LOGO! 8.3 (6ED1052-1CC08-0BA1)",
      "Digital Inputs": "8 (4 can be analog 0–10 V)",
      "Digital Outputs": "4 relay (10 A)",
      "Memory": "400 function blocks",
      "Communication": "Ethernet, Modbus TCP",
      "Programming": "LOGO! Soft Comfort V8.3",
      "Supply Voltage": "24 V DC",
      "Operating Temp": "0 °C to +55 °C",
      "Certifications": "CE, UL, cULus",
      "Mounting": "DIN rail 35 mm",
    },
  },
  {
    id: "P005",
    name: "Keysight U1232A Handheld DMM — 6000 Count",
    category: "electronics",
    price: 198.00,
    originalPrice: 245.00,
    rating: 4.5,
    reviews: 876,
    prime: true,
    badge: null,
    image: "dmm",
    description: "Rugged handheld digital multimeter designed for field engineers and technicians.",
    specs: {
      "Display": "6000 counts, dual LCD",
      "DC Voltage": "600 mV – 1000 V",
      "AC Voltage": "600 mV – 750 V (True RMS)",
      "Current": "600 µA – 10 A",
      "Resistance": "600 Ω – 60 MΩ",
      "Capacitance": "1000 nF – 10 mF",
      "Diode Test": "2.0 V",
      "Safety": "CAT III 600 V",
      "Ingress Protection": "IP54",
      "Weight": "400 g (with holster)",
    },
  },
  {
    id: "P006",
    name: "Eppendorf Research plus Pipette 8-Channel 10-100 µL",
    category: "lab",
    price: 1249.00,
    originalPrice: 1399.00,
    rating: 4.8,
    reviews: 234,
    prime: false,
    badge: "Lab Certified",
    image: "pipette",
    description: "Adjustable 8-channel micropipette with high-precision spring-loaded tip cone.",
    specs: {
      "Volume Range": "10 – 100 µL",
      "Channels": "8",
      "Increment": "0.1 µL",
      "Systematic Error": "±0.8%",
      "Random Error": "≤0.3%",
      "Autoclavable": "121 °C, 20 min (lower part)",
      "Tip Type": "Eppendorf epT.I.P.S.",
      "Material": "PVDF, stainless steel, PPE",
      "Calibration": "ISO 8655 compliant",
      "Weight": "210 g",
    },
  },
  {
    id: "P007",
    name: "Carbon Fiber Sheet 500×500×2mm — 3K Twill Weave",
    category: "materials",
    price: 68.99,
    originalPrice: 84.99,
    rating: 4.4,
    reviews: 567,
    prime: true,
    badge: "Deal",
    image: "carbon",
    description: "High-modulus carbon fiber laminate plate for structural and aerospace prototyping.",
    specs: {
      "Dimensions": "500 × 500 × 2 mm",
      "Weave Pattern": "3K Twill 2×2",
      "Fiber Type": "Toray T300, 3K",
      "Tensile Strength": "≥3500 MPa (fiber direction)",
      "Elastic Modulus": "230 GPa",
      "Density": "1.55 g/cm³",
      "Surface Finish": "Matte / semi-gloss",
      "Max Service Temp": "120 °C (continuous)",
      "Void Content": "<2%",
      "Standard": "ASTM D3039 / D790",
    },
  },
  {
    id: "P008",
    name: "3M SecureFit SF300 Safety Goggles — Anti-Fog",
    category: "safety",
    price: 24.99,
    originalPrice: 29.99,
    rating: 4.6,
    reviews: 3421,
    prime: true,
    badge: "Best Seller",
    image: "goggles",
    description: "Industrial safety goggles with Pressure Diffusion Temple Technology for all-day comfort.",
    specs: {
      "Lens Material": "Polycarbonate (2.0 mm)",
      "UV Protection": "99.9% UVA/UVB",
      "Anti-Fog Coating": "3M Scotchgard",
      "Impact Rating": "ANSI Z87.1+, CSA Z94.3",
      "Field of View": "Wide panoramic",
      "Frame Material": "Nylon with TPR temples",
      "Weight": "28 g",
      "Ventilation": "Indirect vent (splash resistant)",
      "Compatibility": "Over prescription glasses",
      "Standards": "EN166, AS/NZS 1337.1",
    },
  },
  {
    id: "P009",
    name: "MATLAB & Simulink Student Suite — 1 Year License",
    category: "software",
    price: 99.00,
    originalPrice: 149.00,
    rating: 4.7,
    reviews: 4521,
    prime: true,
    badge: "Digital Download",
    image: "matlab",
    description: "Complete numerical computing environment for engineering analysis and simulation.",
    specs: {
      "License Type": "Student — 1 year subscription",
      "Included Toolboxes": "Simulink, Control System, Signal Processing",
      "Supported OS": "Windows 10/11, macOS 12+, Ubuntu 20.04+",
      "RAM Requirement": "8 GB minimum (16 GB recommended)",
      "Disk Space": "32 GB",
      "File Formats": ".mat, .slx, .m, HDF5, CSV",
      "Cloud Access": "MATLAB Online included",
      "Updates": "Automatic for license period",
      "Support": "Community + documentation",
      "Delivery": "Instant digital download",
    },
  },
  {
    id: "P010",
    name: "Oscilloscope Probe Set 100 MHz — 10:1 / 1:1 Switchable",
    category: "electronics",
    price: 34.99,
    originalPrice: 49.99,
    rating: 4.3,
    reviews: 1234,
    prime: true,
    badge: null,
    image: "probe",
    description: "High-bandwidth passive probe set compatible with most bench oscilloscopes.",
    specs: {
      "Bandwidth": "DC – 100 MHz (-3 dB)",
      "Attenuation": "1:1 / 10:1 switchable",
      "Input Resistance": "1 MΩ (1:1), 10 MΩ (10:1)",
      "Input Capacitance": "95 pF (1:1), 15 pF (10:1)",
      "Max Input Voltage": "300 V RMS (10:1)",
      "Compensation Range": "10 – 35 pF",
      "Cable Length": "1.2 m",
      "Connector": "BNC male",
      "Rise Time": "≤3.5 ns",
      "Accessories": "Spring hooks, ground clips, tips",
    },
  },
  {
    id: "P011",
    name: "Hakko FX-951 Soldering Station — 75W",
    category: "tools",
    price: 329.00,
    originalPrice: 379.00,
    rating: 4.8,
    reviews: 987,
    prime: true,
    badge: "Professional",
    image: "solder",
    description: "Digital temperature-controlled soldering station with rapid heat recovery.",
    specs: {
      "Power Output": "75 W",
      "Temperature Range": "200 – 480 °C",
      "Temperature Stability": "±3 °C (idle)",
      "Tip Compatibility": "Hakko T15 series",
      "Heating Element": "Composite ceramic heater",
      "Recovery Time": "30 sec (200→380 °C)",
      "ESD Safe": "Yes — tip grounded",
      "Display": "Digital LED",
      "Sleep Mode": "Auto sleep after 30 min",
      "Weight (handpiece)": "30 g",
    },
  },
  {
    id: "P012",
    name: "Arduino Portenta H7 — Dual-Core IoT Module",
    category: "automation",
    price: 103.50,
    originalPrice: 115.00,
    rating: 4.5,
    reviews: 678,
    prime: true,
    badge: "New",
    image: "arduino",
    description: "High-performance IoT module with STM32H747 dual-core MCU and Wi-Fi/BT connectivity.",
    specs: {
      "MCU": "STM32H747XI — Cortex-M7 @ 480 MHz + M4 @ 240 MHz",
      "RAM": "8 MB SDRAM + 2 MB QSPI Flash",
      "Wireless": "Murata 1DX (Wi-Fi 802.11b/g/n, BT 5.1)",
      "Video": "MIPI DSI, 8-bit camera",
      "GPIO": "80+ via high-density connectors",
      "Analog I/O": "12-bit ADC, DAC",
      "Crypto": "HW acceleration (AES, TRNG)",
      "Programming": "Arduino IDE, Mbed OS, OpenMV",
      "Supply Voltage": "5 V USB-C",
      "Dimensions": "66 × 25.4 mm",
    },
  },
];

/**
 * Bulk pricing tiers for company orders page
 */
const BULK_TIERS = [
  { min: 1, max: 9, discount: 0, label: "Standard" },
  { min: 10, max: 49, discount: 0.08, label: "Volume — 8% off" },
  { min: 50, max: 199, discount: 0.15, label: "Business — 15% off" },
  { min: 200, max: Infinity, discount: 0.22, label: "Enterprise — 22% off" },
];

/**
 * Sample company orders for the B2B dashboard
 */
const SAMPLE_ORDERS = [
  {
    id: "PO-2026-00482",
    company: "Gulf Engineering Corp.",
    date: "2026-05-28",
    status: "Delivered",
    items: 12,
    total: 18450.00,
    contact: "Ahmed Al-Rashid",
  },
  {
    id: "PO-2026-00479",
    company: "Precision Tech LLC",
    date: "2026-05-25",
    status: "In Transit",
    items: 8,
    total: 7230.50,
    contact: "Sarah Mitchell",
  },
  {
    id: "PO-2026-00471",
    company: "National Power Grid",
    date: "2026-05-20",
    status: "Processing",
    items: 45,
    total: 89200.00,
    contact: "James Chen",
  },
  {
    id: "PO-2026-00465",
    company: "BioLab Research Institute",
    date: "2026-05-15",
    status: "Delivered",
    items: 6,
    total: 15680.00,
    contact: "Dr. Maria Santos",
  },
  {
    id: "PO-2026-00458",
    company: "AutoDrive Systems Inc.",
    date: "2026-05-10",
    status: "Cancelled",
    items: 3,
    total: 2100.00,
    contact: "Robert Kim",
  },
];
